### Word Embedding Techniques using Embedding Layer in Keras

In [1]:
!pip install tensorflow-gpu

  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


In [2]:
import tensorflow as tf
print(tf.__version__)

2.19.0


In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
]

In [5]:
# vocabulary size
voc_size = 10000

#### One Hot representation

In [6]:
onehot_repr = [one_hot(words, voc_size) for words in sent]
print(onehot_repr)

[[4169, 3077, 845, 2212], [4169, 3077, 845, 1707], [4169, 9543, 845, 3701], [2025, 9166, 3686, 1868, 4734], [2025, 9166, 3686, 1868, 3499], [8274, 4169, 5474, 845, 8947], [5994, 8731, 564, 1868]]


#### Word Embedding Representation

In [8]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

import numpy as np

In [9]:
sent_length = 8

# pre-padding
embedded_docs = pad_sequences(onehot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4169 3077  845 2212]
 [   0    0    0    0 4169 3077  845 1707]
 [   0    0    0    0 4169 9543  845 3701]
 [   0    0    0 2025 9166 3686 1868 4734]
 [   0    0    0 2025 9166 3686 1868 3499]
 [   0    0    0 8274 4169 5474  845 8947]
 [   0    0    0    0 5994 8731  564 1868]]


In [10]:
dim = 10

In [11]:
model = Sequential()
model.add(Embedding(voc_size, 10, input_length=sent_length))
model.compile('adam', 'mse')

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0, 4169, 3077,  845, 2212], dtype=int32)

In [14]:
model.predict(np.expand_dims(embedded_docs[0], axis=0))

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None
  • kwargs=<class 'inspect._empty'>

In [13]:
print(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 964ms/step
[[[-9.16297361e-03  3.41897868e-02 -3.22832242e-02  2.30961703e-02
   -2.14084517e-02 -9.93154943e-04 -1.07519031e-02 -3.43576558e-02
   -2.00156569e-02  2.87823752e-03]
  [-9.16297361e-03  3.41897868e-02 -3.22832242e-02  2.30961703e-02
   -2.14084517e-02 -9.93154943e-04 -1.07519031e-02 -3.43576558e-02
   -2.00156569e-02  2.87823752e-03]
  [-9.16297361e-03  3.41897868e-02 -3.22832242e-02  2.30961703e-02
   -2.14084517e-02 -9.93154943e-04 -1.07519031e-02 -3.43576558e-02
   -2.00156569e-02  2.87823752e-03]
  [-9.16297361e-03  3.41897868e-02 -3.22832242e-02  2.30961703e-02
   -2.14084517e-02 -9.93154943e-04 -1.07519031e-02 -3.43576558e-02
   -2.00156569e-02  2.87823752e-03]
  [-4.55352776e-02 -2.90586483e-02 -4.37019952e-02 -1.87478960e-04
   -1.91302188e-02  3.34011391e-03 -2.74793040e-02  2.43115537e-02
   -2.05536969e-02 -3.63903046e-02]
  [ 2.29507685e-03 -3.98297422e-02  4.24726047e-02 -1.90595742e-02
   -1.17455348e-02  2.06803158e-03 -4.753607

In [ ]:
sent1 = [
    'The world is a better place',
    'Marvel series is my favourite movie',
    'I like DC movies',
    'the cat is eating the food',
    'Tom and Jerry is my favourite movie',
    'Python is my favourite programming language'
]